version: "3.3"
services:
  database:
    build: database
  front:
    build: front
    tty: true
    ports:
      - 6900:3000
    volumes:
      - ./front/sechack365:/sechack365
  server:
    build: server
    tty: true
    ports:
      - 3300:3300
    volumes:
      - ./server/sechack365:/go/src/github.com/sk409/sechack365
      - /var/run/docker.sock:/var/run/docker.sock
